
#include "gpio.h"

#include "pin_defs.h"

#include "stm32wl55xx.h"
#include "stm32wlxx_ll_gpio.h"
#include "stm32wlxx_ll_exti.h"
#include "stm32wlxx_ll_bus.h"
#include "stm32wlxx_ll_system.h"


void GPIO_init(void)
{
  LL_GPIO_InitTypeDef GPIO_InitStruct = {0};

  /* GPIO Ports Clock Enable */
  LL_AHB2_GRP1_EnableClock(LL_AHB2_GRP1_PERIPH_GPIOA);
  LL_AHB2_GRP1_EnableClock(LL_AHB2_GRP1_PERIPH_GPIOB);

  /*Configure GPIO pin Output Level */
  LL_GPIO_ResetOutputPin(STATUS_LED_PORT, STATUS_LED_PIN);
  LL_GPIO_ResetOutputPin(STATUS_LED_CTRLN_PORT, STATUS_LED_CTRL1_PIN);
  LL_GPIO_SetOutputPin(STATUS_LED_CTRLN_PORT, STATUS_LED_CTRL0_PIN);

  /*Configure Status LED GPIO Pin */
  GPIO_InitStruct.Pin = STATUS_LED_PIN;
  GPIO_InitStruct.Mode = LL_GPIO_MODE_OUTPUT;
  GPIO_InitStruct.Pull = LL_GPIO_PULL_NO;
  GPIO_InitStruct.Speed = LL_GPIO_SPEED_FREQ_LOW;
  LL_GPIO_Init(STATUS_LED_PORT, &GPIO_InitStruct);

  /*Configure Status LED Control GPIO Pins */
  GPIO_InitStruct.Pin = STATUS_LED_CTRL0_PIN | STATUS_LED_CTRL1_PIN;
  GPIO_InitStruct.Mode = LL_GPIO_MODE_OUTPUT;
  GPIO_InitStruct.Pull = LL_GPIO_PULL_NO;
  GPIO_InitStruct.Speed = LL_GPIO_SPEED_FREQ_LOW;
  LL_GPIO_Init(STATUS_LED_CTRLN_PORT, &GPIO_InitStruct);


  // configure GPIO pins for LPUART1 communication
  GPIO_InitStruct.Pin = UART_TX_PIN | UART_RX_PIN;
  GPIO_InitStruct.Mode = LL_GPIO_MODE_ALTERNATE;
  GPIO_InitStruct.Pull = LL_GPIO_PULL_NO;
  GPIO_InitStruct.Speed = LL_GPIO_SPEED_FREQ_MEDIUM;
  GPIO_InitStruct.OutputType = LL_GPIO_OUTPUT_PUSHPULL;
  GPIO_InitStruct.Alternate = LL_GPIO_AF_8;
  LL_GPIO_Init(UART_PORT, &GPIO_InitStruct);


  // ********** configure GPIO pins for outputting IR signal *****************
  // start by setting output low on the IR pins
  LL_GPIO_ResetOutputPin(IR_SIGNALS_PORT, IR_MOD_PIN | IR_CARRIER_PIN);

  // the IR signal is generated by 2 open-drain pins pulling the same resistor low
  // this code configures the IR pins as open drain outputs being driven by TIM16/17

  GPIO_InitStruct.Pin = IR_MOD_PIN | IR_CARRIER_PIN;
  GPIO_InitStruct.Mode = LL_GPIO_MODE_ALTERNATE;
  GPIO_InitStruct.Pull = LL_GPIO_PULL_UP;
  GPIO_InitStruct.Speed = LL_GPIO_SPEED_FREQ_LOW;
  GPIO_InitStruct.OutputType = LL_GPIO_OUTPUT_OPENDRAIN;
  GPIO_InitStruct.Alternate = LL_GPIO_AF_14;
  LL_GPIO_Init(IR_SIGNALS_PORT, &GPIO_InitStruct);

  // set output signal low until transmitting IR signal
  // mode is switched to alternate immediately before transmitting IR signal

  GPIO_IR_Pins_Disable();

}

void GPIO_IR_Pins_Enable(void)
{
  LL_GPIO_SetPinMode(IR_SIGNALS_PORT, IR_MOD_PIN | IR_CARRIER_PIN, LL_GPIO_MODE_ALTERNATE);
}

void GPIO_IR_Pins_Disable(void)
{
  LL_GPIO_SetPinMode(IR_SIGNALS_PORT, IR_MOD_PIN | IR_CARRIER_PIN, LL_GPIO_MODE_OUTPUT);
}